### ISSUE TITLE
Graphics corruption with Shadow of the Beast and Shadow Dancer when using 60820 cpu 

### ISSUE THREAD

**Issue by Oktoras** [MiSTer-devel/Minimig-AGA_MiSTer#101]
I think this started when turbo options were chaged to d-cache sometime last year. Now, this corruption occurs regardless of the D-cache setting.

If one changes cpu to 68000 corruption does not occur.

**Comment by sorgelig** [comment]
This is why 68000 mode exists.
68020 mode is much faster than even real 68020, so some games may fail to work - this is normal.

**Comment by Oktoras** [comment]
Yeah, I forgot to say that this is WHDLoad version, and one should think that it should work. And I am pretty sure it worked with old version of Minimig sometime last year. And it still works with Minimig-mist (where there is still turbo options present). Not critical issue though because as you said 68000 exists.

**Comment by sorgelig** [comment]
68020 on MiSTer is faster than on MiST. It's possible additional performance may be critical for this game. WHDLoad sometimes fails to adjust the performance because TG68K core (68020 CPU) doesn't follow amount of cycles per each instruction, so in some cases in WHDLoad it can be faster or slower than supposed to be.

**Comment by Oktoras** [comment]
Yeah fair enough.

Should we just close this case or do you want to keep it open for now?

**Comment by ransom1122** [comment]
Both games fine in 68020.

ShadowDancer_v1.2_0202.lha & ShadowOfTheBeast_v2.5_1357.lha

Both WHDLoad and my converted single game HDF's work fine. No issues whatsoever.

Im using Amiga Core 21.03.06

And my config is...

CPU - 68020
D-Cache - Off
Chipset - AGA
Chip - 2MB
Fast - 384MB
Slow - none
Rom - Kick31.rom
HRTmon - disabled
TV Standard - PAL
Pixel Clock - 28MHz

Maybe you have an outdated Game WHDLoad slave or your config is incorrect. Or you are using a bad Amiga OS ClassicWB

**Comment by Oktoras** [comment]
That does not work for me. I have clean WB3.1 installation, Kickstart 3.1 for A1200, same whdload game version and still I got the corruption with 68020 cpu. 

With 68000 cpu (and of course, with Kickstart 3.1 for A500, because A1200 kickstart I have does not boot with 68000 cpu) within same hard disk image and same whdload version of game, everything works. 

EDIT. Tested also with KS3.1 for a500, with 68020 cpu, and I got graphics corruption. Changed to ECS, still corruption. Only when cpu is 68000 all is good. Also, in Shadow of the Beast, corruption happens only inside of game, not in title screen.

**Comment by ransom1122** [comment]
As I said it works at my end

I need to know... 
1. Your exact amiga config, all of your config options...
2.  The exact filename of the kickstart you are using?
3.  Exactly where sotb & shadowdancer gfx fails?

**Comment by Oktoras** [comment]
OK, here it comes.

68020 CPU
D-Cache OFF
Chipset AGA
Chip 1M
Fast 8M
Slow None
ROM: Kico31-a1200.rom (md5sum: 646773759326fbac3b2311fd8c8793ee)
HRTmon disabled
TV Standard: PAL
Scandoubler FX: off
video area by: Blank
Aspect Ratio: Original
Pixel Clock: Adaptive
Scaling: Normal
RTG Upscaling: Normal
Stereo Mix: 25%
Audio filter: Auto(LED)
Model: A1200
Paula Output: Normal

Kickstart version: 40.68
Workbench version: 40.42
WHDLoad version: 18.5.5948

Shadow of the Beast (taken from whdownload) slave version 2.5

Some MiSTer.ini settings:
refresh_max=71
refresh_min=48
video_mode=4
forced_scandoubler=1
composite_sync=0
vga_scaler=1
vscale_border=0
dvi_mode=1
vsync_adjust=2

Video is connected via io board VGA to my Eizo 17" LCD monitor.
See screenshot from mister and picture from the screen.

EDIT. I have tested SDRAM on my MiSTer and it runs successfully at 150Mhz. Any faster will produce errors. Minimig core version is newest updated via update.sh script

![20210422_175122-screen](https://user-images.githubusercontent.com/46781085/115763773-7c98f200-a3ad-11eb-8106-35b1e927367a.png)
![IMG_20210422_205245187](https://user-images.githubusercontent.com/46781085/115763780-7e62b580-a3ad-11eb-92b0-013e6be18582.jpg)

**Comment by rsn8887** [comment]
The problem is your pixel clock setting: don't use "adaptive" use "28 MHz", then everything works.

**Comment by rsn8887** [comment]
I can reproduce this (using latest core).

**Comment by Oktoras** [comment]
It seems that this is fixed with latest update. I cannot reproduce this anymore. 

```
Minimig:
- Reworked IDE, support for CDROM (data-only for now).
- Tweaks in LED filters.
- RTG: some tweaks for better stability.
- Update both 68000 and 68020 CPU modules.
- Updated framework.
```

**Comment by rsn8887** [comment]
It still happens for me. Maybe you did something else to fix it?

**Comment by Oktoras** [comment]
Oh, right. It seems that for some reason I do not get graphics corruption in Shadow of the Beast if I do not skip intro (whdload 2.5). If I do, graphics corruption is still there.

**Comment by c0d3h4x0r** [comment]
I am able to repro this in the latest version of this core. The key repro step is to enable the "Skip Intro" option for this WHDLoad game, using either the ToolTypes or the WHDLoad configuration options in the game's WHDLoad splash screen. When "Skip Intro" is enabled, I get this exact graphic corruption. When "Skip Intro" is disabled, the corruption does not repro. This may be a bug with this specific game's WHDLoad slave/installer, which should probably be reported to that slave/installer author.
