### ISSUE TITLE
Score graphics corruption in Hybris

### ISSUE THREAD

**Issue by MilanPolle** [MiSTer-devel/Minimig-AGA_MiSTer#73]
If you look at the image, you can see that the shadow behind the score is incorrect. It works correctly on WinUAE.
[https://imgur.com/bPQmPmE](url)
This was confirmed by another user at the MiSTer forum [https://misterfpga.org/viewtopic.php?f=4&t=698](url)

I found a clue to what is probably the cause of this in an interview with the developer: [https://codetapper.com/amiga/interviews/martin-pedersen/](url)

"The game makes heavy use of sprite tricks! (Disabling sprites in an emulator yields a very empty screen!) Can you recall any interesting stories about the development of the sprite routines?

The biggest effort on the sprites was the score sprites "on top of everything". The rest of the sprites are grouped in such a way that no problems occur in practice.

The score panel at the top of the screen uses a nice trick where sprites 0 and 1 have their sprite data set and are repositioned horizontally across the screen "racing the beam". Did you come up with that effect or had you seen it in another game?

Good description of what actually goes on technically :-)

This was Torben's idea and was not seen on the Amiga before. There was an immense amount of fiddling to make this fit. It is essentially timed down to the exact processor cycle ;-)"

So they are following the display update based on processor cycle timing, to change the sprites at the right time. Then I remembered reading somewhere that the CPU speed of the Minimig core for MiSTer is not exactly the same as on a real Amiga. I guess that could be what is causing this problem.

**Comment by sorgelig** [comment]
did you test in 68000 mode?

**Comment by MilanPolle** [comment]
Yes, forgot to mention the config was simulating an Amiga 500. Kick 1.3 from Amiga forever.

**Comment by ransom1122** [comment]
So I take it no fix for this?

**Comment by sorgelig** [comment]
> So I take it no fix for this?

everybody is waiting when you will fix it.

**Comment by MilanPolle** [comment]
I think I found another problem in the attract mode that might be related (enemy score list, bottom enemy (base) vertical position jittering). I'll have to double check to make sure.

**Comment by rsn8887** [comment]
Robinson5 has been working on MIST/TC64 Minimig core and made some fixes there.

There's a Hybris scoreboard fix which might be interesting to help fix this problem on MiSTer as well, here
https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/7abd0e3fb8594ae2ae6e6b36a3ee32fca6b7ad61
and here:
https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/b0b8d98c3a59018ad008e6ee81f34198021ec4dd

It might also depend on other commits.

**Comment by rsn8887** [comment]
I compiled my own test core with the changes from the above mentioned two commits from the MinimigAGA-MIST-TC64 staging branch by Robinson5, and it indeed fixes the corruption in Hybris on MiSTer core!

Before:

![20240119_183032-screen](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/assets/13071547/f3ec3ddf-5487-4890-9e0c-903b23c53106)

After:

![20240119_182736-screen](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/assets/13071547/4da9f715-0961-460e-91c6-b4fa79a5618f)

Notice the "Score" letters on top left.

Test core: 
[Minimig_test.rbf.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/13996046/Minimig_test.rbf.zip)

**Comment by MilanPolle** [comment]
That is great news! I will test it, I hope it fixes the jittering base unit in the score overview as well.

**Comment by MilanPolle** [comment]
I can confirm that the score shadow problem is fixed with this test version. That is a great improvement! 

The base position jittering in the score overview is still there, so that is caused by a different timing inaccuracy of the implementation of the custom chips.

**Comment by rsn8887** [comment]
I wonder if this fix breaks anything else? It would be good to test other games that use sprites in funny ways, like the energy display in Super Stardust AGA.

**Comment by rsn8887** [comment]
Fixed with release 20240409

**Comment by vanfanel** [comment]
@rsn8887 It seems that part of the problem is still present: The base position jittering/stuttering in the score overview is still there, as @MilanPolle said.

Maybe Robinson5 doesn't know about it? Should we tell him? This is the last remaning OCS game bug I know about in the core... It's a pitty OCS implementation is still wrong, I would gladly pay so we all get proper OCS open implementation.

**Comment by MilanPolle** [comment]
@vanfanel this bug is indeed still there. But this ticket is also not closed yet.

**Comment by vanfanel** [comment]
I even have several Amiga 500 computers stored that I would gladly donate for reverse-engineering efforts. Also 1200.

**Comment by rsn8887** [comment]
I tried the following other MinimigAGA-MIST-TC64 commits by robinsonb5, but none of them helped with the remaining juttering problem in the attract mode score display.

https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/52cb034ad519ce92a96e26a428a30061d26abb80

https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/fe2db716c1cf7cd7f5b5e7cddb5b7b1ffeec5766

https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/ce28f7996651c9034baff3c9ddb711ecbad305b8

https://github.com/retrofun/MinimigAGA-MiST-TC64/commit/7b0f0cfebb8b22905b4d1d2fbdf9d19dce1659dc

**Comment by vanfanel** [comment]
@ransom1122 I have been testing Hybris (floppy, no WHDLoad) on the latest version of the core with plain 68000 and OCS, and I can't see any problem on the score table scrolling anymore.

Can you please confirm you see the same?

I am amazed since recent commits by our master Sorgelig didn't seem related to this bug, but it seems fixed here!

This is the latest available build, as far as I know:

https://github.com/MiSTer-unstable-nightlies/Minimig-AGA_MiSTer/releases/download/unstable-builds/Minimig_unstable_20250127_19368f.rbf

**Comment by vanfanel** [comment]
@ransom1122 Disregard my previous message.. I was booting the floppy in NTSC video mode, where the hiccups don't happen. But they are there in PAL :(
No need to test anything, the bug is still there.

**Comment by rsn8887** [comment]
If you wait on the title screen until this sequence and focus on the circled gray cannon object next to the "...250 points" text, you can see the object jitter up and down a bit. That problem happens together with the jittery PAL scrolling during the same part of the sequence: 

<img width="561" height="559" alt="Image" src="https://github.com/user-attachments/assets/820a98c7-170f-48e3-b012-cddce6e30398" />

I am not sure if it means anything, but maybe if that object's jitter can be fixed, it might also help with the jittery scrolling?

It could very well be that there are three separate Hybris PAL version bugs related to timing:
1) In-game top left score display shadow (already fixed a long time ago on MiSTer thanks to the fix from robinsonb5)
2) Jittery object in demo sequence score list (circled object in picture above trembles up and down a pixel)
3) jittery scrolling, not perfectly smooth, in some parts of demo sequence.

**Comment by sorgelig** [comment]
try with latest commit

**Comment by vanfanel** [comment]
> try with latest commit

It's fixed now, indeed! Thanks to @kblood for all the effort he put on this fix, bringing the OCS implementation to apparent perfection!

@MilanPolle I think this longstanding bug report can be closed now, at last :)

**Comment by MilanPolle** [comment]
That is great news! Hopefully the accuracy of this core is now at least on par with software emulators. I will test it myself and when I've confirmed it, I will close this issue.

**Comment by MilanPolle** [comment]
Confirmed! On the really nice14 inch CRT+DVD that I bought this week, for only €7,50 😄
Perfectly smooth now, it looks fantastic. Congratulations to all involved in making this happen! Respect for your perseverance.

I will happily close this issue now 🎉

**Comment by vanfanel** [comment]
> Confirmed! On the really nice14 inch CRT+DVD that I bought this week, for only €7,50 😄 Perfectly smooth now, it looks fantastic. Congratulations to all involved in making this happen! Respect for your perseverance.
> 
> I will happily close this issue now 🎉

Was nice to see this fixed, indeed! Made me very happy, too, seeing the OCS getting perfected like this at long last! :)
